server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: idempotency-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/**
              filters:
                - RewritePath=/api/(?<segment>.*), /idempotency/${segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway